# Auth Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: shrinkurl/auth
          env:
            - name: JWT_SECRET
              value: "vQoPyhW4tJ7Ty0G4XfTvgtxqRfnMViKLfIDtMJoDmHFM1YxVFbF6z3Y"
            - name: SALT_ROUNDS
              value: "2"
            - name: PORT
              value: "8000"
          ports:
            - containerPort: 8000
---
# Auth service
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 8000
      targetPort: 8000
